# Generated by Django 4.1.6 on 2023-02-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_alter_pet_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="weight",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pet",
            name="age",
            field=models.IntegerField(),
        ),
    ]
